### ISSUE TITLE
python3版本报错ValueError: signature check error

### ISSUE THREAD

**Issue by pythonohtyp** [open-dingtalk/dingtalk-callback-Crypto#9]
前几天好好的，今天2021.6.7就报错了。msg_signature ， sign 这俩有时候相等有时候不等

e67d6e5d3895d19e5441ee35ec0abf6aa4735300 e67d6e5d3895d19e5441ee35ec0abf6aa4735300
{'CorpId': 'dingc5898d74ea40425facaaa37764f94726', 'EventType': 'user_modify_org', 'UserId': ['manager5091'], 'OptStaffId': 'manager5091', 'TimeStamp': '1623060875680'}
ef2292239bf57e0e4a653ab808b9b450f6e9485b ef2292239bf57e0e4a653ab808b9b450f6e9485b
{'CorpId': 'dingc5898d74ea40425facaaa37764f94726', 'EventType': 'user_modify_org', 'UserId': ['manager5091'], 'OptStaffId': 'manager5091', 'TimeStamp': '1623060875733'}
10.0.3.189 - - [07/Jun/2021 18:14:35] "POST /getcallback?signature=e67d6e5d3895d19e5441ee35ec0abf6aa4735300&msg_signature=e67d6e5d3895d19e5441ee35ec0abf6aa4735300&timestamp=1623060875680&nonce=6clubcaE HTTP/1.1" 200 -
a2db01cb3705a585c6b74b24e6bb25ba6a8c4998 5cfffa86aa457189dcd4b9287b26683f7e63541f
[2021-06-07 18:14:35,757] ERROR in app: Exception on /getcallback [POST]
Traceback (most recent call last):
  File "D:\dingOa\lib\site-packages\flask-2.0.0-py3.7.egg\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\dingOa\lib\site-packages\flask-2.0.0-py3.7.egg\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\dingOa\lib\site-packages\flask-2.0.0-py3.7.egg\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\dingOa\lib\site-packages\flask-2.0.0-py3.7.egg\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:/dingOa/api.py", line 23, in callback
    decryptMsg = dingCrypto.getDecryptMsg(arg['msg_signature'], arg['timestamp'], arg['nonce'], jsondata['encrypt'])
  File "D:\dingOa\DingCallbackCrypto.py", line 53, in getDecryptMsg
    raise ValueError('signature check error')
ValueError: signature check error

**Comment by chzealot** [comment]
最新版本测试OK
